In [13]:
import tensorflow as tf
import random

x_data= [[72.,80.,75.], [93.,88.,93],[89.,91.,90.],[96.,98.,100.],
        [73.,66.,70.]]
y_data=[[152.],[185.],[180.],[196.],[142.]]

W = tf.Variable(tf.random.normal([3,1]))
b = tf.Variable(tf.random.normal([1]))

In [25]:
@tf.function
def cost():
    hypothesis = tf.matmul(x_data, W) + b
    cost = tf.reduce_mean(tf.square(hypothesis - y_data))
    return cost

opt = tf.optimizers.Adam(lr=0.01)
for step in range(2001):
    hypo = tf.matmul(x_data, W) + b
    opt.minimize(cost, var_list=[W,b])
    if step % 20 == 0:
        print("step: ",step)
        print("cost: ",cost().numpy())
        print("hypothesis: \n",hypo.numpy())
        print("=======================")


step:  0
cost:  0.1880208
hypothesis: 
 [[153.9906 ]
 [187.09277]
 [183.02654]
 [199.39499]
 [144.45526]]
step:  20
cost:  0.46514517
hypothesis: 
 [[152.3121 ]
 [185.06825]
 [181.03145]
 [197.22322]
 [142.90926]]
step:  40
cost:  0.22975786
hypothesis: 
 [[151.7629 ]
 [184.4058 ]
 [180.37863]
 [196.51262]
 [142.4034 ]]
step:  60
cost:  0.19181056
hypothesis: 
 [[151.69759]
 [184.32703]
 [180.30098]
 [196.42813]
 [142.34325]]
step:  80
cost:  0.1878592
hypothesis: 
 [[151.7089 ]
 [184.34065]
 [180.31438]
 [196.44276]
 [142.35367]]
step:  100
cost:  0.18686499
hypothesis: 
 [[151.68048]
 [184.30637]
 [180.28056]
 [196.40599]
 [142.32748]]
step:  120
cost:  0.18680541
hypothesis: 
 [[151.67798]
 [184.30334]
 [180.27756]
 [196.40277]
 [142.3252 ]]
step:  140
cost:  0.18680112
hypothesis: 
 [[151.68002]
 [184.30579]
 [180.27994]
 [196.40541]
 [142.32707]]
step:  160
cost:  0.186799
hypothesis: 
 [[151.68024]
 [184.30603]
 [180.28014]
 [196.40569]
 [142.32727]]
step:  180
cost:  0.1868022
h

step:  1260
cost:  0.18671677
hypothesis: 
 [[151.68156]
 [184.30516]
 [180.27489]
 [196.40747]
 [142.32828]]
step:  1280
cost:  0.18670784
hypothesis: 
 [[151.68164]
 [184.30519]
 [180.27483]
 [196.40758]
 [142.32835]]
step:  1300
cost:  0.18670884
hypothesis: 
 [[151.68169]
 [184.3052 ]
 [180.2747 ]
 [196.40765]
 [142.3284 ]]
step:  1320
cost:  0.18670788
hypothesis: 
 [[151.68176]
 [184.3052 ]
 [180.27458]
 [196.40773]
 [142.32845]]
step:  1340
cost:  0.18670699
hypothesis: 
 [[151.68178]
 [184.30516]
 [180.27443]
 [196.40776]
 [142.32846]]
step:  1360
cost:  0.1867023
hypothesis: 
 [[151.68182]
 [184.30518]
 [180.27429]
 [196.40784]
 [142.32852]]
step:  1380
cost:  0.18670198
hypothesis: 
 [[151.68184]
 [184.30511]
 [180.27412]
 [196.40787]
 [142.32852]]
step:  1400
cost:  0.18669471
hypothesis: 
 [[151.68185]
 [184.30505]
 [180.27394]
 [196.40787]
 [142.32852]]
step:  1420
cost:  0.18670048
hypothesis: 
 [[151.68208]
 [184.30527]
 [180.27403]
 [196.40819]
 [142.32872]]
step:  1440

In [26]:
import numpy as np

In [28]:
!git clone https://github.com/hunkim/DeepLearningZeroToAll.git

'DeepLearningZeroToAll'에 복제합니다...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 1688 (delta 2), reused 6 (delta 2), pack-reused 1678
오브젝트를 받는 중: 100% (1688/1688), 733.45 KiB | 937.00 KiB/s, 완료.
델타를 알아내는 중: 100% (1101/1101), 완료.


In [33]:
cd DeepLearningZeroToAll

[Errno 2] No such file or directory: 'DeepLearningZeroToAll'
/Users/yeonsookim/Desktop/code/DeepLearningZeroToAll


In [32]:
ls

CONTRIBUTING.md
README.md
chainer/
data-01-test-score.csv
data-02-stock_daily.csv
data-03-diabetes.csv
data-04-zoo.csv
ipynb/
keras/
lab-01-basics.ipynb
lab-02-1-linear_regression.py
lab-02-2-linear_regression_feed.py
lab-02-3-linear_regression_tensorflow.org.py
lab-03-1-minimizing_cost_show_graph.py
lab-03-2-minimizing_cost_gradient_update.py
lab-03-3-minimizing_cost_tf_optimizer.py
lab-03-X-minimizing_cost_tf_gradient.py
lab-04-1-multi_variable_linear_regression.py
lab-04-2-multi_variable_matmul_linear_regression.py
lab-04-3-file_input_linear_regression.py
lab-04-4-tf_reader_linear_regression.py
lab-05-1-logistic_regression.py
lab-05-2-logistic_regression_diabetes.py
lab-06-1-softmax_classifier.py
lab-06-2-softmax_zoo_classifier.py
lab-07-1-learning_rate_and_evaluation.py
lab-07-2-linear_regression_without_min_max.py
lab-07-3-linear_regression_min_max.py
lab-07-4-mnist_introduction.py
lab-08-tensor_manipulation.ipynb
lab-09-1-xor.py
lab-09-2-xor-nn.py
lab-09-3-xor-nn-wide-deep.py
lab

In [34]:
xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:, [-1]]

print(x_data.shape, x_data, len(x_data))
print(y_data.shape, y_data, len(y_data))

(25, 3) [[ 73.  80.  75.]
 [ 93.  88.  93.]
 [ 89.  91.  90.]
 [ 96.  98. 100.]
 [ 73.  66.  70.]
 [ 53.  46.  55.]
 [ 69.  74.  77.]
 [ 47.  56.  60.]
 [ 87.  79.  90.]
 [ 79.  70.  88.]
 [ 69.  70.  73.]
 [ 70.  65.  74.]
 [ 93.  95.  91.]
 [ 79.  80.  73.]
 [ 70.  73.  78.]
 [ 93.  89.  96.]
 [ 78.  75.  68.]
 [ 81.  90.  93.]
 [ 88.  92.  86.]
 [ 78.  83.  77.]
 [ 82.  86.  90.]
 [ 86.  82.  89.]
 [ 78.  83.  85.]
 [ 76.  83.  71.]
 [ 96.  93.  95.]] 25
(25, 1) [[152.]
 [185.]
 [180.]
 [196.]
 [142.]
 [101.]
 [149.]
 [115.]
 [175.]
 [164.]
 [141.]
 [141.]
 [184.]
 [152.]
 [148.]
 [192.]
 [147.]
 [183.]
 [177.]
 [159.]
 [177.]
 [175.]
 [175.]
 [149.]
 [192.]] 25


In [45]:
W = tf.Variable(tf.random.normal([3,1]))
b = tf.Variable(tf.random.normal([1]))

def cost():
    hypothesis = tf.matmul(x_data, W) + b
    cost = tf.reduce_mean(tf.square(hypothesis - y_data))
    return cost

opt = tf.optimizers.Adam(lr=0.1)
for step in range(2001):
    hypo = tf.matmul(x_data, W) + b
    opt.minimize(cost, var_list=[W,b])
    if step % 20 == 0:
        print("step: ",step)
        print("cost: ",cost().numpy()
        print("=======================")

print("Your score will be ", tf.matmul([[100.,70.,101.]], W)+ b)

step:  0
cost:  35003.047
step:  20
cost:  2602.3784
step:  40
cost:  212.03658
step:  60
cost:  20.163202
step:  80
cost:  26.019653
step:  100
cost:  19.536186
step:  120
cost:  19.295763
step:  140
cost:  18.931965
step:  160
cost:  18.663528
step:  180
cost:  18.382473
step:  200
cost:  18.091553
step:  220
cost:  17.792324
step:  240
cost:  17.486176
step:  260
cost:  17.174501
step:  280
cost:  16.858604
step:  300
cost:  16.539701
step:  320
cost:  16.218884
step:  340
cost:  15.897186
step:  360
cost:  15.575586
step:  380
cost:  15.254902
step:  400
cost:  14.935977
step:  420
cost:  14.619523
step:  440
cost:  14.306216
step:  460
cost:  13.996693
step:  480
cost:  13.691475
step:  500
cost:  13.391086
step:  520
cost:  13.095975
step:  540
cost:  12.806516
step:  560
cost:  12.5230665
step:  580
cost:  12.245951
step:  600
cost:  11.975424
step:  620
cost:  11.711719
step:  640
cost:  11.454992
step:  660
cost:  11.205437
step:  680
cost:  10.963143
step:  700
cost:  10.7282

In [ ]:
# 배치 관련 더 고민해보자.


xy = np.loadtxt('data-01-test-score.csv', delimiter=',', dtype=np.float32)
x_data = xy[:,0:-1]
y_data = xy[:, [-1]]

W = tf.Variable(tf.random.normal([3,1]))
b = tf.Variable(tf.random.normal([1]))

def cost():
    hypothesis = tf.matmul(x_data, W) + b
    cost = tf.reduce_mean(tf.square(hypothesis - y_data))
    return cost



opt = tf.optimizers.Adam(lr=0.1)
for step in range(2001):
    hypo = tf.matmul(x_data, W) + b
    x_batch, y_batch = 
    opt.minimize(cost, var_list=[W,b])
    if step % 20 == 0:
        print("step: ",step)
        print("cost: ",cost().numpy())
        print("=======================")

print("Your score will be ", tf.matmul([[100.,70.,101.]], W)+ b)