In [1]:
import tensorflow as tf

In [39]:
import tensorflow as tf
import random 

x1_data = [73., 93., 89., 96., 73.]
x2_data = [80., 88., 91.,98.,66.]
x3_data = [75.,93.,90.,100.,70.]
y_data = [152.,185.,180.,196.,142.]

w1 = tf.Variable(random.random())
w2 = tf.Variable(random.random())
w3 = tf.Variable(random.random())
b = tf.Variable(random.random())

@tf.function
def hypothesis():
    hypo = x1_data * w1 + x2_data * w2 + x3_data * w3 + b
    return hypo

@tf.function
def cost():
    hypothesis = x1_data * w1 + x2_data * w2 + x3_data * w3 + b
    cost = tf.reduce_mean(tf.square(hypothesis-y_data))
    return cost

opt = tf.optimizers.Adam(lr=1e-5)
for step in range(2001):
    opt.minimize(cost, var_list=[w1,w2,w3,b])
    hypo = hypothesis()
    if step%100 ==0:
        print(step,"\n", cost().numpy(),"\n", hypo.numpy())



0 
 8843.562 
 [68.89942 83.8136  82.0606  88.41435 65.14547]
100 
 8795.119 
 [69.12841 84.08859 82.33159 88.70934 65.35547]
200 
 8746.9 
 [69.35698  84.36307  82.60208  89.003784 65.56507 ]
300 
 8698.895 
 [69.585175 84.6371   82.872116 89.29774  65.77432 ]
400 
 8651.064 
 [69.81314  84.910866 83.1419   89.591415 65.98338 ]
500 
 8603.387 
 [70.041016 85.18451  83.411575 89.884964 66.192345]
600 
 8555.905 
 [70.26858  85.457794 83.68087  90.17811  66.40105 ]
700 
 8508.635 
 [70.49576  85.730606 83.949715 90.47077  66.60937 ]
800 
 8461.559 
 [70.72265 86.00305 84.21821 90.76305 66.81741]
900 
 8414.662 
 [70.94928 86.27522 84.48641 91.05499 67.02525]
1000 
 8367.912 
 [71.17584 86.54729 84.75453 91.34685 67.23302]
1100 
 8321.321 
 [71.40226  86.8192   85.022484 91.63854  67.44065 ]
1200 
 8274.906 
 [71.62845  87.090836 85.29015  91.92992  67.6481  ]
1300 
 8228.69 
 [71.85431  87.36206  85.557434 92.22088  67.85522 ]
1400 
 8182.6553 
 [72.079926 87.63297  85.82443  92.511505 